### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an HTML, CSS, and JavaScript file
- [x] Create the background 
- [x] Place the car image on the screen
