### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location property with x and y coordinates to the car data model
- [x] Listen to the `document` for a `keydown` event from space bar
     - [x] Use a `boolean` to keep track of the car state
- [x] Car moves every 16 millisecond
     - [x] Use `setInterval` and update car coordinates
